"""Generate the committed semconv contract module from weaver's resolved JSON.

Pure transform: reads a JSON file, writes a Python file. No network, no Docker.
Invoked by `make -C .semconv generate` as:

    python -m opentelemetry.semconv_ai._contract._generator --resolved ... --out ...
"""

import argparse
import json
from pathlib import Path
from typing import Dict

from opentelemetry.semconv_ai._contract import (
    AttributeSpec,
    SpanSpec,
    enum_members_of,
    parse_requirement_level,
)

BANNER = '''"""The OpenTelemetry GenAI semantic-convention contract, as Python.

DO NOT EDIT. Generated by opentelemetry.semconv_ai._contract._generator from the
registry vendored in .semconv/, pinned at the SHA below. Regenerate with:

    make -C .semconv generate
"""

from opentelemetry.semconv_ai._contract import AttributeSpec, Level, SpanSpec

CONTRACT_REF = "{ref}"

SPANS = {{
'''


def build_specs(resolved: Dict) -> Dict[str, SpanSpec]:
    """Convert weaver's resolved registry into SpanSpec objects, keyed by group id."""
    specs: Dict[str, SpanSpec] = {}

    for group in resolved.get("groups", []):
        if group.get("type") != "span":
            continue

        attributes = []
        for attr in group.get("attributes", []):
            # Weaver back-fills requirement_level during resolution, so every
            # resolved attribute carries one. A missing key means upstream changed
            # shape — fail loudly rather than silently downgrading a required
            # attribute to non-blocking in the conformance harness.
            try:
                raw_level = attr["requirement_level"]
            except KeyError:
                raise SystemExit(
                    f"attribute {attr.get('name')!r} in group {group['id']!r} has no "
                    "requirement_level; the resolved registry changed shape"
                ) from None
            level, condition = parse_requirement_level(raw_level)
            attributes.append(
                AttributeSpec(
                    name=attr["name"],
                    level=level,
                    condition=condition,
                    enum_members=enum_members_of(attr.get("type")),
                )
            )

        # Sorted so regeneration produces a stable, reviewable diff.
        attributes.sort(key=lambda a: a.name)

        if group["id"] in specs:
            raise SystemExit(f"duplicate span group id in resolved registry: {group['id']!r}")

        specs[group["id"]] = SpanSpec(
            id=group["id"],
            span_kind=group.get("span_kind"),
            attributes=tuple(attributes),
        )

    return specs


def _render_attribute(attr: AttributeSpec) -> str:
    members = (
        "None"
        if attr.enum_members is None
        else "(" + "".join(f"{m!r}, " for m in attr.enum_members) + ")"
    )
    return (
        f"            AttributeSpec({attr.name!r}, Level.{attr.level.name}, "
        f"{attr.condition!r}, {members}),\n"
    )


def render(specs: Dict[str, SpanSpec], ref: str) -> str:
    """Render the specs as an importable Python module. Deterministic."""
    out = [BANNER.format(ref=ref)]

    for span_id in sorted(specs):
        spec = specs[span_id]
        out.append(f"    {span_id!r}: SpanSpec(\n")
        out.append(f"        id={spec.id!r},\n")
        out.append(f"        span_kind={spec.span_kind!r},\n")
        out.append("        attributes=(\n")
        for attr in spec.attributes:
            out.append(_render_attribute(attr))
        out.append("        ),\n")
        out.append("    ),\n")

    out.append("}\n\n__all__ = [\"CONTRACT_REF\", \"SPANS\"]\n")
    return "".join(out)


def _pinned_ref() -> str:
    # .../packages/<pkg>/opentelemetry/semconv_ai/_contract/_generator.py -> repo root
    repo_root = Path(__file__).resolve().parents[5]
    versions = repo_root / ".semconv" / "versions.env"
    for line in versions.read_text().splitlines():
        if line.startswith("SEMCONV_GENAI_REF="):
            return line.split("=", 1)[1].strip()
    raise SystemExit("SEMCONV_GENAI_REF not found in .semconv/versions.env")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--resolved", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    resolved = json.loads(args.resolved.read_text())
    specs = build_specs(resolved)
    if not specs:
        raise SystemExit("no span groups found — is the resolved registry correct?")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(specs, ref=_pinned_ref()))
    print(f"wrote {args.out} ({len(specs)} span groups)")


if __name__ == "__main__":
    main()
