[tool.poetry]
name = "langserve_example"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
langchain-community = "^0.0.38"
langchain-text-splitters = "^0.0.1"
langchain = "^0.1.20"
openai = "^1.29.0"
chromadb = "^0.5.0"
tiktoken = "^0.7.0"
beautifulsoup4 = "^4.12.3"

[tool.poetry.dependencies.traceloop-sdk]
path = "../traceloop-sdk"
develop = true

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
