[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/milvus" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-milvus"
version = "0.21.5"
description = "OpenTelemetry Milvus instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-milvus"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/milvus"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.25.0"
opentelemetry-semantic-conventions = "^0.46b0"
opentelemetry-instrumentation = "^0.46b0"
opentelemetry-semantic-conventions-ai = "0.2.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.1.0"
flake8 = "7.0.0"
pytest = "8.1.1"
pytest-sugar = "1.0.0"
pymilvus = "^2.4.1"

[tool.poetry.group.test.dependencies]
pymilvus = "^2.4.1"
pytest = "8.1.1"
pytest-sugar = "1.0.0"
opentelemetry-sdk = "^1.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["milvus"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
milvus = "opentelemetry.instrumentation.milvus:MilvusInstrumentor"
