[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opentelemetry-instrumentation-milvus"
version = "0.43.0"
description = "OpenTelemetry Milvus instrumentation"
authors = [
    {name = "Gal Kleinman", email = "gal@traceloop.com"},
    {name = "Nir Gazit", email = "nir@traceloop.com"},
    {name = "Tomer Friedman", email = "tomer@traceloop.com"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "opentelemetry-api>=1.28.0",
    "opentelemetry-semantic-conventions>=0.50b0",
    "opentelemetry-instrumentation>=0.50b0",
    "opentelemetry-semantic-conventions-ai",
]
instruments = ["milvus"]

[project.optional-dependencies]
dev = [
    "autopep8>=2.2.0",
    "flake8>=7.1.2",
    "pytest>=8.2.2",
    "pytest-sugar>=1.0.0",
    "pymilvus>=2.4.1",
]
test = [
    "pymilvus>=2.4.1",
    "pytest>=8.2.2",
    "pytest-sugar>=1.0.0",
    "opentelemetry-sdk>=1.27.0",
]

[project.entry-points."opentelemetry_instrumentor"]
milvus = "opentelemetry.instrumentation.milvus:MilvusInstrumentor"

[project.urls]
Repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-milvus"

[tool.hatch.build.targets.wheel]
packages = ["opentelemetry"]

[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/milvus"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true
